#define LTOK_IDENTIFIER                      1
#define LTOK_CONSTANT                        2
#define LTOK_STRING_LITERAL                  3
#define LTOK_LPARENS                         4
#define LTOK_RPARENS                         5
#define LTOK_LBRACKET                        6
#define LTOK_RBRACKET                        7
#define LTOK_DOT                             8
#define LTOK_PTR_OP                          9
#define LTOK_INC_OP                         10
#define LTOK_DEC_OP                         11
#define LTOK_COMMA                          12
#define LTOK_SIZEOF                         13
#define LTOK_AND                            14
#define LTOK_MULT                           15
#define LTOK_PLUS                           16
#define LTOK_MINUS                          17
#define LTOK_TILDE                          18
#define LTOK_BANG                           19
#define LTOK_DIV                            20
#define LTOK_MOD                            21
#define LTOK_LEFT_OP                        22
#define LTOK_RIGHT_OP                       23
#define LTOK_LESS                           24
#define LTOK_MORE                           25
#define LTOK_LE_OP                          26
#define LTOK_GE_OP                          27
#define LTOK_EQ_OP                          28
#define LTOK_NE_OP                          29
#define LTOK_XOR                            30
#define LTOK_OR                             31
#define LTOK_ANDAND_OP                      32
#define LTOK_OROR_OP                        33
#define LTOK_QUESTIONMARK                   34
#define LTOK_COLON                          35
#define LTOK_EQUALS                         36
#define LTOK_MUL_ASSIGN                     37
#define LTOK_DIV_ASSIGN                     38
#define LTOK_MOD_ASSIGN                     39
#define LTOK_ADD_ASSIGN                     40
#define LTOK_SUB_ASSIGN                     41
#define LTOK_LEFT_ASSIGN                    42
#define LTOK_RIGHT_ASSIGN                   43
#define LTOK_AND_ASSIGN                     44
#define LTOK_XOR_ASSIGN                     45
#define LTOK_OR_ASSIGN                      46
#define LTOK_SEMICOLON                      47
#define LTOK_TYPEDEF                        48
#define LTOK_EXTERN                         49
#define LTOK_STATIC                         50
#define LTOK_VOID                           51
#define LTOK_CHAR                           52
#define LTOK_SHORT                          53
#define LTOK_INT                            54
#define LTOK_LONG                           55
#define LTOK_FLOAT                          56
#define LTOK_DOUBLE                         57
#define LTOK_SIGNED                         58
#define LTOK_UNSIGNED                       59
#define LTOK_TYPE_NAME                      60
#define LTOK_LBRACE                         61
#define LTOK_RBRACE                         62
#define LTOK_STRUCT                         63
#define LTOK_UNION                          64
#define LTOK_ENUM                           65
#define LTOK_CONST                          66
#define LTOK_VOLATILE                       67
#define LTOK_ELLIPSIS                       68
#define LTOK_CASE                           69
#define LTOK_DEFAULT                        70
#define LTOK_IF                             71
#define LTOK_ELSE                           72
#define LTOK_SWITCH                         73
#define LTOK_WHILE                          74
#define LTOK_DO                             75
#define LTOK_FOR                            76
#define LTOK_GOTO                           77
#define LTOK_CONTINUE                       78
#define LTOK_BREAK                          79
#define LTOK_RETURN                         80
